{{- if .Values.storage.customPVEnabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "cloudconnectors.fullname" . }}-persistent-storage
  namespace: {{ template "cloudconnectors.namespace" . }}
  labels:
{{- include "cloudconnectors.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
    {{- toYaml .Values.storage.accessModes | nindent 4 }}
  persistentVolumeReclaimPolicy: {{ .Values.storage.reclaimPolicy }}
  storageClassName: {{ .Values.storage.storageClassName }}
  hostPath:
    path: {{ include "cloudconnectors.storagePath" . }}
{{- end }}
