{{- if .Values.rbac.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cloudconnectors.serviceAccountName" . }}
  namespace: {{ template "cloudconnectors.namespace" . }}
  labels:
{{- include "cloudconnectors.labels" . | nindent 4 }}
  {{- if .Values.rbac.serviceAccount.annotations }}
  annotations:
    {{- range $key, $value := .Values.rbac.serviceAccount.annotations }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
