exporters:
  otlp_grpc/axorouter:
    endpoint: ${env:AXOROUTER_ENDPOINT}
    retry_on_failure:
      enabled: true
      max_elapsed_time: 0
    sending_queue:
      enabled: true
      storage: file_storage
    tls:
      insecure: ${env:AXOROUTER_TLS_INSECURE:-false}
      ca_file: ${env:AXOROUTER_TLS_CA_FILE}
      ca_pem: ${env:AXOROUTER_TLS_CA_PEM}
      cert_file: ${env:AXOROUTER_TLS_CERT_FILE}
      cert_pem: ${env:AXOROUTER_TLS_CERT_PEM}
      key_file: ${env:AXOROUTER_TLS_KEY_FILE}
      key_pem: ${env:AXOROUTER_TLS_KEY_PEM}
      min_version: ${env:AXOROUTER_TLS_MIN_VERSION:-1.2}
      max_version: ${env:AXOROUTER_TLS_MAX_VERSION}
      include_system_ca_certs_pool: ${env:AXOROUTER_TLS_INCLUDE_SYSTEM_CA_CERTS_POOL:-false}
      insecure_skip_verify: ${env:AXOROUTER_TLS_INSECURE_SKIP_VERIFY:-false}

processors:
  resource/axoflow_device_id:
    attributes:
      - key: "com.axoflow.device_id"
        action: insert
        value: "${env:AXOCLOUDCONNECTOR_DEVICE_ID}"

  resourcedetection/system:
    detectors: ["system", "env"]
    system:
      hostname_sources: ["dns", "os", "cname", "lookup"]
      resource_attributes:
        host.name:
          enabled: true
        host.ip:
          enabled: true
        host.id:
          enabled: true

  resource/axoflow: # Provider specific!
    attributes:
      - key: "com.axoflow.vendor"
        action: insert
        value: "tenable"
      - key: "com.axoflow.product"
        action: insert
        value: "vulnerability-management"

receivers: # Provider specific!
  tenable_audit_log:
    endpoint: ${env:TENABLE_ENDPOINT:-https://cloud.tenable.com}
    access_key: ${env:TENABLE_ACCESS_KEY}
    secret_key: ${env:TENABLE_SECRET_KEY}
    poll_interval: ${env:TENABLE_POLL_INTERVAL:-5m}
    page_size: ${env:TENABLE_PAGE_SIZE:-1000}
    max_records_per_poll: ${env:TENABLE_MAX_RECORDS_PER_POLL:-5000}
    initial_lookback: ${env:TENABLE_INITIAL_LOOKBACK:-24h}
    timeout: ${env:TENABLE_TIMEOUT:-30s}
    storage: file_storage
    tls:
      insecure: ${env:TENABLE_TLS_INSECURE:-false}
      insecure_skip_verify: ${env:TENABLE_TLS_INSECURE_SKIP_VERIFY:-false}
      ca_file: ${env:TENABLE_TLS_CA_FILE}
      ca_pem: ${env:TENABLE_TLS_CA_PEM}
      cert_file: ${env:TENABLE_TLS_CERT_FILE}
      cert_pem: ${env:TENABLE_TLS_CERT_PEM}
      key_file: ${env:TENABLE_TLS_KEY_FILE}
      key_pem: ${env:TENABLE_TLS_KEY_PEM}
      min_version: ${env:TENABLE_TLS_MIN_VERSION:-1.2}
      max_version: ${env:TENABLE_TLS_MAX_VERSION}
      include_system_ca_certs_pool: ${env:TENABLE_TLS_INCLUDE_SYSTEM_CA_CERTS_POOL:-false}

extensions:
  health_check:
    endpoint: ${env:POD_IP}:13133
  file_storage:
    directory: ${env:STORAGE_DIRECTORY}
    create_directory: true

service:
  extensions: [health_check, file_storage]
  pipelines:
    logs:
      receivers: [tenable_audit_log]
      processors:
        [resource/axoflow_device_id, resourcedetection/system, resource/axoflow]
      exporters: [otlp_grpc/axorouter]
