receivers:
  azureeventhub:
    connection: ${env:AZURE_EVENT_HUBS_CONNECTION_STRING}
    format: azure
    apply_semantic_conventions: true
    storage: file_storage

processors:
  resource/axoflow:
    attributes:
      - key: "com.axoflow.product"
        action: insert
        value: "azure-event-hubs"

service:
  pipelines:
    logs:
      receivers: [azureeventhub]
      processors: [resource/axoflow]
