exporters:
  otlp/axorouter:
    endpoint: ${env:AXOROUTER_ENDPOINT}
    retry_on_failure:
      enabled: true
      max_elapsed_time: 0
    sending_queue:
      enabled: true
      storage: file_storage
    tls:
      insecure: ${env:AXOROUTER_TLS_INSECURE:-false}
      ca_file: ${env:AXOROUTER_TLS_CA_FILE}
      ca_pem: ${env:AXOROUTER_TLS_CA_PEM}
      cert_file: ${env:AXOROUTER_TLS_CERT_FILE}
      cert_pem: ${env:AXOROUTER_TLS_CERT_PEM}
      key_file: ${env:AXOROUTER_TLS_KEY_FILE}
      key_pem: ${env:AXOROUTER_TLS_KEY_PEM}
      min_version: ${env:AXOROUTER_TLS_MIN_VERSION:-1.2}
      max_version: ${env:AXOROUTER_TLS_MAX_VERSION}
      include_system_ca_certs_pool: ${env:AXOROUTER_TLS_INCLUDE_SYSTEM_CA_CERTS_POOL:-false}
      insecure_skip_verify: ${env:AXOROUTER_TLS_INSECURE_SKIP_VERIFY:-false}

extensions:
  health_check:
    endpoint: ${env:POD_IP}:13133
  file_storage:
    directory: ${env:STORAGE_DIRECTORY}
    create_directory: true

service:
  extensions: [health_check, file_storage]
  pipelines:
    logs:
      exporters: [otlp/axorouter]
