name: Release

on:
  push:
    tags: ["[0-9]+.[0-9]+.[0-9]+*"]

permissions:
  contents: read

jobs:
  image-build:
    name: Image build
    uses: ./.github/workflows/image-build.yaml
    with:
      publish: true
      release: true
    permissions:
      contents: read
      packages: write
      id-token: write
